name: Prisma Cloud IaC Scan

on:
  push:
    branches:
      - main
      - dev
      - 'feature/*'  # Any branch starting with "feature/"
  pull_request:
    branches:
      - main
      - dev
      - 'feature/*'
  schedule:
    - cron: '16 19 * * 0'

permissions:
  contents: read

jobs:
  checkov_iac_scan:
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read  # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: Clear Cache
        run: rm -rf .git/modules
        
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: false  # Prevents fetching submodules

      - name: Run Prisma Cloud Checkov
        id: prisma_cloud
        uses: bridgecrewio/checkov-action@master
        with:
          output_format: sarif  # Ensure the output format is SARIF
          output_file_path: checkov.sarif  # Save to a specified path

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: checkov.sarif  # Directly refer to the SARIF file saved in the previous step
